[package]
name = "envoy-example"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proxy-wasm = "0.1.4"
chrono = "0.4.19"
cfg-if = "1.0.0"
log = "0.4.11"
