version: '3'
services:
  envoy:
    build: ./
    command:
      - --config-path
      - /etc/envoy/envoy.yaml
#      - --log-level
#      - trace
    ports:
      - "8001:8001"
      - "10000:10000"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
  mysql:
    image: mysql:5.6.51
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
